[package]
name = "blackjack"
version = "0.1.0"
authors = ["Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com>"]
edition = "2018"

[dependencies]
rand = "0.3.14"

[lib]
name = "blackjack"
path = "lib/lib.rs"
crate-type = ["lib", "staticlib"]

[[bin]]
name = "blackjack"
path = "src/main.rs"
